project:
  type: book

book:
  title: "Quarto Pearls"
  author: "Kathrine McAulay"
  date: "3/22/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - basics.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



